[package]
name = "client"
version = "0.1.0"
authors = ["James Carl"]
edition = "2018"
license = "AGPL"

[dependencies]
anyhow = "1.0"
argh = "0.1"
base64 = "0.13"
common = { path = "../common" }
# egui = "0.11.0"
# egui_wgpu_backend = "0.6.0"
# egui_winit_platform = "0.6.0"
env_logger = "0.8"
futures = "0.3"
jemallocator = "0.3.2"
legion = "0.4"
log = "0.4"
native-dialog = "0.5"
num-traits = "0.2.12"
platform-dirs = "0.3.0"
rand = "0.8"
rayon = "1.4"
rsa = "0.4"
vk-shader-macros = "0.2.6"
wgpu = "0.8"
winit = "0.24"
chrono = "0.4.19"
bytemuck = "1.4.1"
nalgebra = "0.26"
bytemuck_derive = "1.0.0"
goods = "0.8"
image = "0.23.10"
