[package]
name = "server"
version = "0.1.0"
authors = ["James Carl"]
edition = "2018"
license = "AGPL"

[dependencies]
anyhow = "1.0"
common = { path = "../common" }
env_logger = "0.8"
jemallocator = "0.3"
log = "0.4"
