[package]
name = "entities"
version = "0.1.0"
authors = ["James Carl"]
edition = "2018"
license-file = "../../COPYING"

[lib]
crate-type = ["cdylib"]

[dependencies]
grid_engine_wasm_api = { path = "../../wasm/grid_engine_wasm_api" }
log = "0.4.11"
